### ISSUE TITLE
Multiple rows are sent to graylog at once

### ISSUE THREAD

**Issue by silverasu** [art-ws/pm2-gelf-json#1]
Sometimes pm2-gelf-json sends multiple JSON rows to graylog at once and graylog is unable to parse those rows.
Maybe we should split incomig JSON rows by newline and send one row at a time to graylog?

**Comment by saaivs** [comment]
Good catch. Thank you!

**Comment by art-ws** [comment]
@silverasu Please check vesion `1.0.3`
```sh
pm2 install pm2-gelf-json
pm2 set pm2-gelf-json:graylogLogParseErrors true # Optional
pm2 set pm2-gelf-json:graylogSplitLines true # Fix. Enabled by default.
```
